import React from 'react';
import { Card } from '../ui/Card';
import { Sparkles, BrainCircuit } from 'lucide-react';

interface FeedbackCardProps {
  summary?: string;
  aiDetailedFeedback?: string;
}

export const FeedbackCard: React.FC<FeedbackCardProps> = ({
  summary = 'Demonstrated strong core knowledge of React architecture, reconciliation, and state management lifecycle patterns.',
  aiDetailedFeedback = 'The candidate provided well-structured answers explaining how the Virtual DOM minimizes direct browser layout recalculations using diffing algorithms. Communication was clear with good technical depth. To reach senior mastery, recommend elaborating further on React 18 Fiber architecture and concurrent rendering primitives.',
}) => {
  return (
    <Card padding="lg" className="w-full bg-gradient-to-br from-blue-50/50 to-white border-blue-100">
      <div className="space-y-4">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-primary text-white shadow-sm">
            <BrainCircuit className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-gray-900">AI Assessment Summary</h3>
            <p className="text-xs text-primary font-medium flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5" /> Generated by LLM Evaluation Pipeline
            </p>
          </div>
        </div>

        <div className="p-4 bg-white rounded-xl border border-blue-100 shadow-sm space-y-2">
          <h4 className="text-sm font-semibold text-gray-900">Executive Summary</h4>
          <p className="text-sm text-gray-700 leading-relaxed">{summary}</p>
        </div>

        <div className="space-y-2">
          <h4 className="text-sm font-semibold text-gray-900">Detailed AI Analysis</h4>
          <p className="text-sm text-gray-600 leading-relaxed bg-surface p-4 rounded-xl border border-surface-border">
            {aiDetailedFeedback}
          </p>
        </div>
      </div>
    </Card>
  );
};
