'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { PageContainer } from '@/components/layout/PageContainer';
import { PageHeader } from '@/components/layout/PageHeader';
import { ScoreCircle } from '@/components/common/ScoreCircle';
import { ScoreCard } from '@/components/feedback/ScoreCard';
import { FeedbackCard } from '@/components/feedback/FeedbackCard';
import { StrengthCard } from '@/components/feedback/StrengthCard';
import { WeaknessCard } from '@/components/feedback/WeaknessCard';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { useInterviewContext } from '@/context/InterviewContext';
import {
  Award,
  RotateCcw,
  Home,
  Code2,
  MessageSquare,
  Cpu,
  Zap,
  BookOpen,
  Download,
  Calendar,
  Check,
} from 'lucide-react';

export default function FeedbackPage() {
  const { candidate, report, resetSession } = useInterviewContext();
  const [downloaded, setDownloaded] = useState(false);

  const candidateName = candidate?.name || report?.candidateName || 'John Doe';
  const techDomain = candidate?.technology || report?.technology || 'React';
  const experience = candidate?.experience || '2 Years';
  const role = candidate?.role || 'Frontend Developer';

  const overallScore = report?.feedback.overallScore || 86;
  const scores = report?.feedback.scores || [
    { category: 'technical', title: 'Technical Knowledge', score: 90, maxScore: 100, description: 'Exemplary mastery of core concepts and architecture.' },
    { category: 'communication', title: 'Communication', score: 85, maxScore: 100, description: 'Clear technical prose using standard industry terminology.' },
    { category: 'problemSolving', title: 'Problem Solving', score: 88, maxScore: 100, description: 'Analytical approach to performance trade-offs.' },
    { category: 'confidence', title: 'Confidence', score: 82, maxScore: 100, description: 'Decisive answers with thorough coverage of edge cases.' },
  ];

  const summary = report?.feedback.summary || `Candidate ${candidateName} demonstrated strong core knowledge of ${techDomain} architecture and lifecycle patterns.`;
  const aiDetailedFeedback = report?.feedback.aiDetailedFeedback || `The candidate provided well-structured answers explaining how ${techDomain} handles core runtime challenges. Communication was clear with good technical depth.`;
  const strengths = report?.feedback.strengths || [
    `Deep understanding of ${techDomain} core concepts`,
    'Clear explanations of asynchronous state updates and batching',
    'Effective use of accurate performance terminology',
    'Logical problem-solving breakdown during technical scenarios',
  ];
  const weaknesses = report?.feedback.weaknesses || [
    `Elaborate more on internal ${techDomain} architecture details`,
    'Include practical code examples for optimization scenarios',
    'Mention memory leak prevention when cleaning up side effects',
  ];
  const recommendedTopics = report?.feedback.recommendedTopics || [
    `${techDomain} Internal Architecture`,
    'Advanced Concurrency & Async Patterns',
    'Memory Leak Profiling & Optimization',
    'Production Security & Error Boundaries',
  ];

  const handleExportPDF = () => {
    setDownloaded(true);
    if (typeof window !== 'undefined') {
      window.print();
    }
  };

  return (
    <PageContainer maxWidth="xl" className="space-y-8">
      {/* Top Page Header */}
      <PageHeader
        title="Interview Assessment Report"
        description="Comprehensive evaluation generated by the AI Interview Engine based on candidate responses."
        badge={
          <Badge variant="success" icon={<Award className="w-3.5 h-3.5" />}>
            Evaluation Complete
          </Badge>
        }
        action={
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              icon={downloaded ? <Check className="w-4 h-4 text-success" /> : <Download className="w-4 h-4" />}
              onClick={handleExportPDF}
            >
              {downloaded ? 'PDF Exported' : 'Export PDF'}
            </Button>
            <Link href="/interview" onClick={resetSession}>
              <Button variant="secondary" size="sm" icon={<RotateCcw className="w-4 h-4" />}>
                Retake Interview
              </Button>
            </Link>
          </div>
        }
      />

      {/* Hero Score Overview Row */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
        {/* Overall Score Circle (4 Cols) */}
        <Card padding="lg" className="lg:col-span-4 flex flex-col items-center justify-center text-center bg-gradient-to-b from-blue-50/40 to-white border-blue-100">
          <ScoreCircle score={overallScore} size={150} strokeWidth={12} label="Overall Match Score" />
          <div className="mt-4 pt-4 border-t border-gray-200 w-full flex items-center justify-between text-xs text-gray-500 font-medium">
            <span className="flex items-center gap-1">
              <Calendar className="w-3.5 h-3.5 text-gray-400" /> {report?.completedAt || 'Completed Today'}
            </span>
            <span className="text-success font-semibold">Tier 1 Recommendation</span>
          </div>
        </Card>

        {/* Four Score Metric Cards (8 Cols -> 2x2 Grid) */}
        <div className="lg:col-span-8 grid grid-cols-1 sm:grid-cols-2 gap-4">
          {scores.map((sc, idx) => {
            let icon = <Code2 className="w-5 h-5" />;
            if (sc.category === 'communication') icon = <MessageSquare className="w-5 h-5" />;
            if (sc.category === 'problemSolving') icon = <Cpu className="w-5 h-5" />;
            if (sc.category === 'confidence') icon = <Zap className="w-5 h-5" />;

            return (
              <ScoreCard
                key={idx}
                title={sc.title}
                score={sc.score}
                description={sc.description}
                icon={icon}
              />
            );
          })}
        </div>
      </div>

      {/* AI Assessment & Feedback Details */}
      <FeedbackCard
        summary={summary}
        aiDetailedFeedback={aiDetailedFeedback}
      />

      {/* Strengths vs Areas for Improvement Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <StrengthCard strengths={strengths} />
        <WeaknessCard weaknesses={weaknesses} />
      </div>

      {/* Recommended Learning Topics & Interview Summary */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Recommended Learning Topics (7 Cols) */}
        <Card padding="lg" className="lg:col-span-7 space-y-4">
          <div className="flex items-center gap-2 border-b border-gray-200 pb-3">
            <BookOpen className="w-5 h-5 text-primary" />
            <h3 className="text-lg font-bold text-gray-900">Recommended Learning Topics</h3>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {recommendedTopics.map((topic, idx) => (
              <div key={idx} className="p-3.5 bg-surface border border-surface-border rounded-xl">
                <span className="text-xs font-bold text-primary block">Topic {idx + 1}</span>
                <h4 className="text-sm font-semibold text-gray-900 mt-0.5">{topic}</h4>
                <p className="text-xs text-gray-500 mt-1">Targeted module for reaching senior technical proficiency.</p>
              </div>
            ))}
          </div>
        </Card>

        {/* Interview Summary Card (5 Cols) */}
        <Card padding="lg" className="lg:col-span-5 space-y-4 bg-surface border-surface-border">
          <h3 className="text-lg font-bold text-gray-900 border-b border-gray-200 pb-3">
            Session Metadata
          </h3>

          <div className="space-y-3 text-xs text-gray-600">
            <div className="flex justify-between py-1.5 border-b border-gray-200">
              <span className="font-medium text-gray-500">Candidate Name</span>
              <span className="font-semibold text-gray-900">{candidateName}</span>
            </div>
            <div className="flex justify-between py-1.5 border-b border-gray-200">
              <span className="font-medium text-gray-500">Role</span>
              <span className="font-semibold text-gray-900">{role}</span>
            </div>
            <div className="flex justify-between py-1.5 border-b border-gray-200">
              <span className="font-medium text-gray-500">Technology Domain</span>
              <span className="font-semibold text-gray-900">{techDomain}</span>
            </div>
            <div className="flex justify-between py-1.5 border-b border-gray-200">
              <span className="font-medium text-gray-500">Experience Level</span>
              <span className="font-semibold text-gray-900">{experience}</span>
            </div>
            <div className="flex justify-between py-1.5">
              <span className="font-medium text-gray-500">Completed On</span>
              <span className="font-semibold text-gray-900">{report?.completedAt || 'Today'}</span>
            </div>
          </div>
        </Card>
      </div>

      {/* Bottom Action Footer */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-6 border-t border-gray-200">
        <Link href="/interview" onClick={resetSession} className="w-full sm:w-auto">
          <Button variant="primary" size="lg" fullWidth icon={<RotateCcw className="w-5 h-5" />}>
            Retake Interview
          </Button>
        </Link>
        <Link href="/" onClick={resetSession} className="w-full sm:w-auto">
          <Button variant="secondary" size="lg" fullWidth icon={<Home className="w-5 h-5" />}>
            Go Home
          </Button>
        </Link>
      </div>
    </PageContainer>
  );
}
